authapp/urls.py
from django.urls import path 
from .views import login_view, signup_view, logout_view


app_name = "auth"
urlpatterns = [
    path("login/", login_view, name="login"),
    path("signup/", signup_view, name="signup"),
    path("logout/", logout_view, name="logout")
]

crudapp/urls.py
from django.urls import path

from .views import home_view, add_task_view, update_task_view


app_name = "crud"
urlpatterns = [
    path("", home_view, name="home"),
    path("add-task/", add_task_view, name="add_task"),
    path("update-task/<int:task_id>/", update_task_view, name="update_task")
]

python_aws_curd_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("crudapp.urls")),
    path("auth/", include("authapp.urls"))
]

authapp/models.py
from django.db import models

# Create your models here.

crudapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Task(models.Model):
    name = models.CharField(max_length=200)
    user = models.ForeignKey(User,related_name="user_task", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    
    
    def __str__(self):
        return self.name

authapp/views.py
from django.shortcuts import render
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import redirect


def login_view(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        
        # trying to login user in
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect("crud:home")
        
        # if the username if correct, error password incorrect
        if User.objects.filter(username=username).exists():
            messages.error(request, "Your password is incorrect!")
            return redirect("auth:login")
        else:
            # Error both username and password incorrect.
            messages.error(request, "The username and password provided is invalid")
            return redirect("auth:login")
            
    return render(request, "authapp/login.html")


def signup_view(request):
    if request.method == "POST":
        username = request.POST.get("username")
        email = request.POST.get("email")
        password = request.POST.get("password")
        password2 = request.POST.get("password2")
        
        if password == password2:
            # Check the email already exits
            if User.objects.filter(email=email).exists():
                messages.error(request, f"'{email}' is already in use by another user")
                return redirect("auth:signup")
            if User.objects.filter(username=username).exists():
                messages.error(request, f"'{username}' is already in use by another user")
                return redirect("auth:signup")
            user = User(username=username, email=email)
            user.set_password(password)
            user.save()
            
            account_creation_msg = "Account creation was successful. Please login"
            return render(request, "authapp/login.html", {"account_creation_msg": account_creation_msg})
        
        messages.error(request, "The two passwords do not match!")
        return redirect("auth:signup")
    return render(request, "authapp/signup.html")


def logout_view(request):
    logout(request)
    return redirect("auth:login")

crudapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Task


def get_tasks(user, task_id=None):
    if task_id is None:
        return Task.objects.filter(user=user)
    return Task.objects.get(id=task_id)


@login_required(login_url="auth:login")
def home_view(request):
    context = {"tasks": get_tasks(request.user) }
    return render(request, "crudapp/account.html", context)


@login_required(login_url="auth:login")
def add_task_view(request):
    if request.method == "POST":
        task = request.POST.get("task")
        if task:
            task = Task(name=task, user=request.user)
            task.save()
            return redirect("crud:home")
        messages.error(request, "Please enter a task you want to add")
        return redirect("crud:home")
    return redirect("crud:home")


@login_required(login_url="auth:login")
def update_task_view(request, task_id):
    if request.method == "POST":
        task = request.POST.get("task")
        if task:
            current_task = get_tasks(request.user, task_id)
            current_task.name=task
            current_task.save()
            
            messages.error(request, "Updated successfully")
            return redirect("crud:home")
        
        messages.error(request, "We were unable to update your task")
        return redirect("crud:home")
    
    context = {"task": get_tasks(request.user, task_id)}
    return render(request, "crudapp/update.html", context)

templates/authapp/login.html
{% extends "base.html" %}
{% load static %}

{% block title %} Login {% endblock title %}

{% block content %}

<div class="container main-container">
	<div class="row nm-row">
		<div class="col-lg-7 nm-bgi d-none d-lg-flex">
			<div class="overlay">
				<div class="hero-item hero-item-1">
					<h2>Login to account</h2>
					<h2>Use the app</h2>
				</div>	
			</div>
		</div>
		<div class="col-lg-5 nm-mb-1 nm-mb-md-1 nm-aic">
			<div class="card">
				<div class="card-content">
					<div class="header">
						<p class="h2">DJANGO AWS CRUD APP</p>
						<p class="h2">Login now</p>
					</div>
					<form action="{% url 'auth:login' %}" method="POST">
						{% csrf_token %}
						{% if messages %}
						  {% for msg in messages  %}
							<div style="color: red;">{{msg}}</div>
						  {% endfor %}
						{% endif %}
						<div style="color: green;">{{account_creation_msg}}</div>
						<div class="form-group">
							<label for="inputUsername">Username</label>
							<div class="input-group nm-gp">
								<span class="nm-gp-pp"><i class="fas fa-user"></i></span>
								<input id="inputUsername" name="username" class="form-control" type="text" tabindex="2"  required>
							</div>
						</div>	

						<div class="form-group">
							<label for="inputPassword">Password</label>
							<div class="input-group nm-gp">
								<span class="nm-gp-pp"><i class="fas fa-lock"></i></span>
								<input id="inputPassword" name="password" class="form-control" type="password" tabindex="3"  required>
							</div>
						</div>

						<button type="submit" class="btn btn-block btn-primary nm-btn">Login</button>
						<hr />
						<p class="text-center nm-ft-b nm-wh mb-0">
							Don't have an account?
							<a href="{% url 'auth:signup' %}">Signup</a>
						</p>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock content %}

templates/authapp/recover.html
<!doctype html>
<html lang="en">

<!-- Mirrored from nimoy.ceosdesigns.sk/template/v07/recover.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 29 Jul 2024 20:01:20 GMT -->
<head>
	<!-- // Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Required meta tags // -->

    <meta name="description" content="Login and Register Form HTML Template - developed by 'ceosdesigns' - sold exclusively on 'themeforest.net'">
	<meta name="author" content="ceosdesigns.sk">

    <title>Nimoy · Login and Register Form HTML Template</title>

	<!-- // Favicon -->
	<link href="images/favicon.png" rel="icon">
	<!-- Favicon // -->

	<!-- // Google Web Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600&amp;display=swap" rel="stylesheet">
	<!-- Google Web Fonts // -->
	
	<!-- // Font Awesome 5 Free -->
	<link href="../../../use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous" rel="stylesheet">
	<!-- Font Awesome 5 Free // -->

    <!-- // Template CSS files -->
	<link href="css/bootstrap.min.css" rel="stylesheet">
	<link href="css/styles.css" rel="stylesheet">
	<!-- Template CSS files  // -->
</head>
<body>
	<!-- // Preloader -->
	<div id="nm-preloader" class="nm-aic nm-vh-md-100">
		<div class="nm-ripple">
			<div></div>
			<div></div>
		</div>
	</div>
	<!-- Preloader // -->

	<main class="d-flex">
		<div class="container main-container">
			<div class="row nm-row">
				<div class="col-lg-7 nm-bgi d-none d-lg-flex">
					<div class="overlay">
						<div class="hero-item">
							<a href="../../index-2.html" aria-label="Nimoy">
								<img src="images/logoReversed.png" alt="Logo">
							</a>
						</div>
						<div class="hero-item hero-item-1">
							<h2>Go all the way.</h2>
							<h2>Don't give up. Ever.</h2>
							<h2>It's that simple.</h2>
						</div>	
						<ul class="hero-item">
							<li><a href="#">Home</a></li>
							<li><a href="#">About</a></li>
							<li><a href="#">Contacts</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-5 nm-mb-1 nm-mb-md-1 nm-aic">
					<div class="card">
						<div class="card-content">
							<div class="header">
								<p class="h2">Password Recovery</p>
								<p class="h2">Write it down or somethin...</p>
							</div>
							<form>
								<div class="form-group">
									<label for="inputEmail">Email</label>
									<div class="input-group nm-gp">
										<span class="nm-gp-pp"><i class="fas fa-envelope-open"></i></span>
										<input id="inputEmail" class="form-control" type="email" tabindex="1" placeholder="Email" required>
									</div>
								</div>	

								<button type="submit" class="btn btn-block btn-primary nm-btn">Reset Password</button>

								<p class="divider">Or continue with your social profile:</p>

								<div class="row social nm-mb-1">
									<div class="col-md-6 mb-2 mb-md-0">
										<a href="#" class="btn btn-block nm-btn btn-facebook">
											<i class="fab fa-facebook-f nm-mr-1h"></i>
											Facebook
										</a>
									</div>

									<div class="col-md-6">
										<a href="#" class="btn btn-block nm-btn btn-google">
											<i class="fab fa-google nm-mr-1h"></i>
											Google
										</a>
									</div>
								</div>

								<p class="text-center nm-ft-b nm-wh mb-0">
									I need an account! 
									<a href="signup.html">Signup</a>
								</p>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</main>
	
	<!-- // Vendor JS files -->
	<script src="js/jquery-3.6.0.min.js"></script>
	<script src="js/bootstrap.bundle.min.js"></script>
	<!-- Vendor JS files // -->

	<!-- Template JS files // -->
	<script src="js/script.js"></script>
	<!-- Template JS files // -->

	<!-- ======================================================= -->
	<!-- // Setting to allow preview of different color variants -->
	<!-- ======================================================= -->
	<div id="settings" style="position: fixed; top: 20%; right: 0%; width: 40px; height: 40px; background-color: #000; color: #fff; display: flex; align-items: center; justify-content: center; cursor: pointer;">
		<i class="fas fa-cog"></i>
		<div id="colors" style="position: absolute; top: 40px; left: 40px; width: 40px; height: 240px; background-color: #000;">
			<a id="blue" href="#" style="display: block; width: 40px; height: 40px; background-color: #007bff;"></a>
			<a id="beige" href="#" style="display: block; width: 40px; height: 40px; background-color: #eab8a9;"></a>
			<a id="burgundy" href="#" style="display: block; width: 40px; height: 40px; background-color: #af102e;"></a>
			<a id="fuchsia" href="#" style="display: block; width: 40px; height: 40px; background-color: #600da8;"></a>
			<a id="turquoise" href="#" style="display: block; width: 40px; height: 40px; background-color: #50c8cc;"></a>
			<a href="../../index-2.html" style="display: block; width: 40px; height: 40px; background-color: #000; color: #fff; display: flex; align-items: center; justify-content: center;"><i class="fas fa-home"></i></a>
		</div>
	</div>

	<script>
		let tmpLocation = window.location.href;
		let tmpEndLocation = tmpLocation.split("../../index.html");
		let targetLocation = tmpEndLocation[tmpEndLocation.length-1];
		targetLocation = targetLocation.replace(".html","").replace("#", "");
		let targetLocationArray = [];

		if(targetLocation.includes("_")){
			targetLocationArray = targetLocation.split("_");
			targetLocationArray[1] = "_" + targetLocationArray[1];
		}
		else {
			targetLocationArray[0] = targetLocation;
			targetLocationArray[1] = "";
		}

		let l = document.links;
		for(let i=0; i<l.length; i++) {
			let tmp = l[i].attributes.href.nodeValue;
			l[i].attributes.href.nodeValue = tmp.replace("recover","recover" + targetLocationArray[1]).replace("login","login" + targetLocationArray[1]).replace("signup","signup" + targetLocationArray[1]);
		}

		document.getElementById("blue").setAttribute('href',"./" + targetLocationArray[0] + ".html");
		document.getElementById("beige").setAttribute('href',"./" + targetLocationArray[0] + "_1.html");
		document.getElementById("burgundy").setAttribute('href',"./" + targetLocationArray[0] + "_2.html");
		document.getElementById("fuchsia").setAttribute('href',"./" + targetLocationArray[0] + "_3.html");
		document.getElementById("turquoise").setAttribute('href',"./" + targetLocationArray[0] + "_4.html");

		document.getElementById("colors").style.transition = 'all 0.2s';
		document.getElementById("settings").addEventListener("click", () =>{
			let leftPosition = document.getElementById("colors").style.left;

			if(leftPosition == '40px'){
				document.getElementById("colors").style.left = '0px';
			}
			else {
				document.getElementById("colors").style.left = '40px';
			}
		});
	</script>
	<!-- ======================================================= -->
	<!-- Setting to allow preview of different color variants // -->
	<!-- ======================================================= -->
</body>

<!-- Mirrored from nimoy.ceosdesigns.sk/template/v07/recover.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 29 Jul 2024 20:01:20 GMT -->
</html>

templates/authapp/signup.html
{% extends "base.html" %}
{% load static %}

{% block title %} Sigup {% endblock title %}

{% block content %}

<div class="container main-container">
	<div class="row nm-row">
		<div class="col-lg-7 nm-bgi d-none d-lg-flex">
			<div class="overlay">
				<div class="hero-item hero-item-1">
					<h2>Create an account</h2>
					<h2>Login to account</h2>
					<h2>Use the app</h2>
				</div>	
			</div>
		</div>
		<div class="col-lg-5 nm-mb-1 nm-mb-md-1 nm-aic">
			<div class="card">
				<div class="card-content">
					<div class="header">
						<p class="h2">DJANGO AWS CRUD APP</p>
						<p class="h2">Create an account to get started</p>
					</div>
					<form method="POST" action="{% url 'auth:signup' %}">
						{% csrf_token %}
						{% if messages %}
						  {% for msg in messages  %}
							<div style="color: red;">{{msg}}</div>
						  {% endfor %}
						{% endif %}
						<div class="form-group">
							<label for="inputEmail">Email</label>
							<div class="input-group nm-gp">
								<span class="nm-gp-pp"><i class="fas fa-envelope-open"></i></span>
								<input id="inputEmail" name="email" class="form-control" type="email" tabindex="1" required>
							</div>
						</div>	

						<div class="form-group">
							<label for="inputUsername">Username</label>
							<div class="input-group nm-gp">
								<span class="nm-gp-pp"><i class="fas fa-user"></i></span>
								<input id="inputUsername" name="username" class="form-control" type="text" tabindex="2"  required>
							</div>
						</div>	

						<div class="form-group">
							<label for="inputPassword">Password</label>
							<div class="input-group nm-gp">
								<span class="nm-gp-pp"><i class="fas fa-lock"></i></span>
								<input id="inputPassword" name="password" class="form-control" type="password" tabindex="3"  required>
							</div>
						</div>

						<div class="form-group">
							<label for="inputPassword">Confirm Password</label>
							<div class="input-group nm-gp">
								<span class="nm-gp-pp"><i class="fas fa-lock"></i></span>
								<input id="inputPassword" name="password2" class="form-control" type="password" tabindex="4"  required>
							</div>
						</div>

						<button type="submit" class="btn btn-block btn-primary nm-btn">Sign Up</button>
						<hr />
						<p class="text-center nm-ft-b nm-wh mb-0">
							Already a member?
							<a href="{% url 'auth:login' %}">Login</a>
						</p>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock content %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
	<!-- // Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Required meta tags // -->


    <title>Django AWS CRUD APP | {% block title %} {% endblock title %}</title>


	<!-- // Google Web Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600&amp;display=swap" rel="stylesheet">
	<!-- Google Web Fonts // -->

    <!-- // Template CSS files -->
	<link href="{% static 'authapp/css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'authapp/css/styles.css' %}" rel="stylesheet">
	<!-- Template CSS files  // -->
</head>
<body>

	<main class="d-flex">
{% block content %}
  
{% endblock content %}
	</main>
	
	<!-- // Vendor JS files -->
	<script src="{% static 'authapp/js/jquery-3.6.0.min.js' %}"></script>
	<script src="{% static 'authapp/js/bootstrap.bundle.min.js' %}"></script>
	<!-- Vendor JS files // -->

	<!-- Template JS files // -->
	<script src="{% static 'authapp/js/script.js' %}"></script>
	<!-- Template JS files // -->

	<!-- Setting to allow preview of different color variants // -->
	<!-- ======================================================= -->
</body>

<!-- Mirrored from nimoy.ceosdesigns.sk/template/v07/signup.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 29 Jul 2024 20:01:20 GMT -->
</html>

templates/crudapp/account.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=500">
    <title>To-Do List</title>
	<style>
		body {
			font-family: Arial, sans-serif;
			background-color: #f4f4f4;
			margin: 0;
			padding: 0;
			display: flex;
			justify-content: center;
			align-items: center;
			height: auto;
		}
		
		.container {
			background: white;
			padding: 20px;
			border-radius: 8px;
			box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
			width: 90%;
		}
		
		h1 {
			text-align: center;
			margin-bottom: 20px;
		}
		
		.input-container {
			display: flex;
			justify-content: space-between;
			margin-bottom: 20px;
		}
		
		input[type="text"] {
			flex: 1;
			padding: 10px;
			border: 1px solid #ccc;
			border-radius: 4px;
			margin-right: 10px;
		}
		
		button {
			padding: 10px 20px;
			border: none;
			background-color: #28a745;
			color: white;
			border-radius: 4px;
			cursor: pointer;
		}
		
		button:hover {
			background-color: #218838;
		}
		
		ul {
			list-style-type: none;
			padding: 0;
		}
		
		li {
			padding: 10px;
			border-bottom: 1px solid #ddd;
			display: flex;
			justify-content: space-between;
			align-items: center;
		}
		
		li:last-child {
			border-bottom: none;
		}
		
		li.completed {
			text-decoration: line-through;
			color: #888;
		}
		
		li button {
			background-color: #dc3545;
			border: none;
			color: white;
			padding: 5px 10px;
			border-radius: 4px;
			cursor: pointer;
		}
		
		li button:hover {
			background-color: #c82333;
		}

	</style>
</head>
<body>
    <div class="container">
		<small><a href="{% url 'auth:logout' %}">Logout</a></small>
        <h1>DJANGO AWS CRUD APP</h1>
		<form action="{% url 'crud:add_task' %}" method="post">
			{% csrf_token %}
			{% if messages %}
			  {% for msg in messages  %}
				<div style="color: #d9dc35;">{{msg}}</div>
			  {% endfor %}
			{% endif %}
			<div style="color: green;">{{success_msg}}</div>
			<div class="input-container">
				{% csrf_token %}
				<input type="text" id="taskInput" name="task" placeholder="Add a new task...">
				<button>Add</button>
			</div>
		</form>
        <ul id="taskList">
			{% if tasks %}
			  {% for task in tasks  %}
				<li>{{task}} <span><a href="{% url 'crud:update_task' task.id %}"><button style="background: #28a745">Update</button></a> <a href="#"><button>Delete</button></a></span></li>
			  {% endfor %}
			{% endif %}
		</ul>
    </div>
</body>
</html>

templates/crudapp/update.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=500">
    <title>To-Do List</title>
	<style>
		body {
			font-family: Arial, sans-serif;
			background-color: #f4f4f4;
			margin: 0;
			padding: 0;
			display: flex;
			justify-content: center;
			align-items: center;
			height: auto;
		}
		
		.container {
			background: white;
			padding: 20px;
			border-radius: 8px;
			box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
			width: 90%;
		}
		
		h1 {
			text-align: center;
			margin-bottom: 20px;
		}
		
		.input-container {
			display: flex;
			justify-content: space-between;
			margin-bottom: 20px;
		}
		
		input[type="text"] {
			flex: 1;
			padding: 10px;
			border: 1px solid #ccc;
			border-radius: 4px;
			margin-right: 10px;
		}
		
		button {
			padding: 10px 20px;
			border: none;
			background-color: #28a745;
			color: white;
			border-radius: 4px;
			cursor: pointer;
		}
		
		button:hover {
			background-color: #218838;
		}
		
		ul {
			list-style-type: none;
			padding: 0;
		}
		
		li {
			padding: 10px;
			border-bottom: 1px solid #ddd;
			display: flex;
			justify-content: space-between;
			align-items: center;
		}
		
		li:last-child {
			border-bottom: none;
		}
		
		li.completed {
			text-decoration: line-through;
			color: #888;
		}
		
		li button {
			background-color: #dc3545;
			border: none;
			color: white;
			padding: 5px 10px;
			border-radius: 4px;
			cursor: pointer;
		}
		
		li button:hover {
			background-color: #c82333;
		}

	</style>
</head>
<body>
    <div class="container">
		<small><a href="{% url 'auth:logout' %}">Logout</a></small>
        <h1>Updating '{{task}}'</h1>
        <li>Item name: {{task}}</li>
        <li>Item ID: {{task.id}}</li>
        <li>Created: {{task.created_at}}</li>
        <li>Updated: {{task.update_at}}</li>
		<form action="{% url 'crud:update_task' task.id %}" method="post">
			{% csrf_token %}
			{% if messages %}
			  {% for msg in messages  %}
				<div style="color: #d9dc35;">{{msg}}</div>
			  {% endfor %}
			{% endif %}
			<div class="input-container">
				{% csrf_token %}
				<input type="text" id="taskInput" name="task" value="{{task}}">
				<button>Save Changes</button>
			</div>
		</form>
        <a href="{% url 'crud:home' %}"><button style="background: #dc3545">Cancel</button></a>
    </div>
</body>
</html>